---

- name: "Add ssh keys to routers"
  hosts: router
  connection: ansible.netcommon.network_cli
  gather_facts: 'no'
  vars:
    ansible_user: "vyos"
    ansible_password: "vyos"
    ansible_network_os: vyos.vyos.vyos
    
  tasks:
    - name: Configure remote
      vyos.vyos.vyos_config:
        lines:
          - set system login user vyos authentication public-keys aibix@ubuntu-cluster key 'AAAAC3NzaC1lZDI1NTE5AAAAIFpwtLpKPNExRVDiBNmXwvkrw7DMnkPB7R8B39pcurea'
          - set system login user vyos authentication public-keys aibix@ubuntu-cluster type 'ssh-ed25519'
        save: true
