---
- vars:
    ansible_network_os: vyos.vyos.vyos

- name: Vyos Kram
  hosts: router
  # throttle: 1
  gather_facts: no
  
  tasks:
  - name: configurable backup path
    vyos_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}"
        dir_path: "/home/aibix/streams/ansible_out"


