---

- name: Vyos Kram
  hosts: all
  vars:
    ansible_network_os: vyos.vyos.vyos
  # throttle: 1
  gather_facts: no
  connection: network_cli
  
  tasks:
  - name: configurable backup path
    vyos_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}"
        dir_path: "/home/aibix/streams/ansible_out"


