---
- name: vrf config
  hosts: router
  vars:
    ansible_user: vyos
    ansible_network_os: vyos.vyos.vyos
  gather_facts: no

  connection: network_cli
  
  tasks:
    - name: remove nameserver
      vyos_config:
        lines:
          - delete system name-server
      tags: vyos
      when: os == "vyos"
      
