---

- name: "Add ssh keys to routers"
  hosts: router
  connection: network_cli
  gather_facts: 'no'

  tasks:
    - name: Configure remote
      vyos.vyos.vyos_config:
        lines:
          - set system login user vyos authentication public-keys aibix@automation key 'AAAAC3NzaC1lZDI1NTE5AAAAIHcH6rEhepn76QcVDpRYc/s4i0FIHdFXejYoq4dGinKu'
          - set system login user vyos authentication public-keys aibix@automation type 'ssh-ed25519'
        save: true
