---
- hosts: router
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    ansible_user: "vyos"
    ansible_password: "vyos"
    ansible_network_os: vyos.vyos.vyos

  tasks:
  - name: Gather listed l3 interfaces with provided configurations
    vyos.vyos.vyos_l3_interfaces:
      config:
      state: gathered
    register: gathered_config

  - name: Print gathered config
    debug:
      msg: "{{ gathered_config.gathered }}"

  - name: Print inventory config
    debug:
      msg: "{{ item }}"
    with_items: "{{ interfaces.lo.ipv4_address }}"