---
- name: Fill template
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Fill template using jinja2
    ansible.builtin.template:
      src: ../templates/test.j2
      dest: ../../out/test.txt
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.interface }}"
    when: os == "vyos"
    delegate_to: localhost
