---
- name: Get latest VyOS ISO and deploy on routers for upgrading.
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: vyos.vyos.vyos

  hosts: router
  tasks:

    - name: Get latest VyOS ISO URL
      uri: 
        url: https://raw.githubusercontent.com/vyos/vyos-nightly-build/refs/heads/current/version.json
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: data

    - name: Extract the ISO URL from content
      set_fact:
        iso_url: "{{ (data.content | from_json)[0].url }}"

    - name: Debug iso_url
      debug:
        var: iso_url

    - name: Set fact iso_name from url
      set_fact:
        iso_name: "{{ iso_url.split('/')[-1] }}"

    - name: Check if the image already exists
      stat:
        path: "/tmp/{{ iso_name }}"
      register: image_stat

    - name: Download ISO if it does not exist
      get_url:
        url: "{{ iso_url }}"
        dest: "/tmp/{{ iso_name }}"
      when: not image_stat.stat.exists

    - name: Upload vyos.iso to router
      net_put:
        src: "/tmp/{{ iso_name }}"
        dest: "{{ iso_name }}"

    - name: "Installing latest vyos on system"
      cli_command:
        command: add system image "{{ iso_name }}"
        newline: True
        check_all: True
        prompt:
        - 'What would you like to name this image'
        - 'Would you like to set the new image as the default one for boot'
        - 'An active configuration was found'
        - 'Would you like to copy SSH host keys'
        answer:
        - ''
        - 'y'
        - 'y'
        - 'y'

    - name: reboot
      cli_command:
        command: "reboot now"
      #when: reboot is defined
