---

- name: Fill template
  hosts: router
  connection: network_cli
  gather_facts: false

  tasks:
  - debug: msg='{{ ansible_run_tags }}'
    tags: ['debug']
    when: "'debug' in ansible_run_tags"

  - name: Generate config using jinja2
    ansible.builtin.template:
      src: setup-mit-set.j2
      dest: out/{{ ansible_hostname }}-setup.cfg
    delegate_to: localhost

