---
- name: Fill template
  hosts: router
  connection: local
  gather_facts: false

  tasks:
  - name: Fill template using jinja2
    ansible.builtin.template:
      src: roles/cfgtpl/templates/test.j2
      dest: out/test.txt
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.interface }}"
    when: os == "vyos"
    delegate_to: localhost
