---

- name: Fill template
  hosts: router
  connection: network_cli
  gather_facts: false

  tasks:
  - debug: msg='{{ ansible_run_tags }}'
    tags: ['debug']
    when: "'debug' in ansible_run_tags"

  - name: Delete config
    vyos.vyos.vyos_config:
      lines:
        - delete protocols bgp
        - delete protocols mpls
        - delete protocols ospf
        - delete protocols static
        - delete interfaces wireguard wg0
        - delete interfaces br100
      save: true
    tags: ['delete']
    when: "'delete' in ansible_run_tags"

  - name: Generate config using jinja2
    ansible.builtin.template:
      src: setup.j2
      dest: out/{{ ansible_hostname }}-setup.cfg
    delegate_to: localhost

  - name: Remove Whitespaces
    ansible.builtin.command:
      cmd: sed -i 's/^\s*//' out/{{ ansible_hostname }}-setup.cfg
    delegate_to: localhost

  - name: Deploy config
    vyos.vyos.vyos_config:
      src: out/{{ ansible_hostname }}-setup.cfg
      backup: true
