---

- name: "Add ssh keys to routers"
  hosts: router
  connection: ansible.netcommon.network_cli
  gather_facts: 'no'
  vars:
    ansible_user: "vyos"
    ansible_password: "vyos"
    ansible_network_os: vyos.vyos.vyos
    
  tasks:
    - name: Configure remote
      vyos.vyos.vyos_config:
        lines:
          - delete protocols ospf
          - delete protocols ospfv3
        save: true
