---
- name: Setup vyos config
  hosts: router
  vars:
    ansible_user: vyos
    ansible_network_os: vyos.vyos.vyos
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Write config to device using jinja2
      vyos.vyos.vyos_config:
        src: ../templates/vyos-setup.j2
        save: true

    - name: Write config using jinja2
      ansible.builtin.template:
        src: ../templates/vyos-setup.j2
        dest: ../out/{{ ansible_hostname }}-ansible.txt
        mode: '0644'
      delegate_to: localhost
      tags: ['test']
      when: "'test' in ansible_run_tags"
